version: '3.4'

services:
  vue:
    container_name: vue
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      # - '.:/app'
      - ./src:/app/src
    ports:
      - "5050:8080"
    restart: on-failure
    tty: true
    stdin_open: true
